name: Test Solutions

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  check-empty:
    runs-on: ubuntu-latest
    outputs:
      should-run: ${{ steps.check-files.outputs.should-run }}
    steps:
      - uses: actions/checkout@v3
      
      - name: Check if solution files are non-empty
        id: check-files
        run: |
          # Check each solution file and set output if any is non-empty
          should_run=false
          for file in solution.c solution.cpp Solution.java solution.py; do
            if [ -f "$file" ] && [ -s "$file" ]; then
              echo "Found non-empty solution file: $file"
              should_run=true
            fi
          done
          
          if [ "$should_run" = true ]; then
            echo "should-run=true" >> $GITHUB_OUTPUT
          else
            echo "All solution files are empty or missing"
            echo "should-run=false" >> $GITHUB_OUTPUT
          fi

  run-tests:
    needs: check-empty
    if: needs.check-empty.outputs.should-run == 'true'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        language: [c, cpp, java, python]
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        if: matrix.language == 'python'
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          
      - name: Set up JDK
        if: matrix.language == 'java'
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          
      - name: Set up C/C++
        if: matrix.language == 'c' || matrix.language == 'cpp'
        run: sudo apt-get update && sudo apt-get install -y gcc g++
        
      - name: Run Python tests
        if: matrix.language == 'python'
        run: |
          python -m pip install pytest
          python -m pytest tests/test_solution.py -v
          
      - name: Run Java tests
        if: matrix.language == 'java'
        run: |
          javac Solution.java Test.java
          java Test
          
      - name: Run C tests
        if: matrix.language == 'c'
        run: |
          gcc solution.c test.c -o test_program
          ./test_program
          
      - name: Run C++ tests
        if: matrix.language == 'cpp'
        run: |
          g++ solution.cpp test.cpp -o test_program
          ./test_program